server:
  port: 33333
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/testapp_V2
  kafka:
    consumer:
      bootstrap-servers: ${kafka.bootstrap}
      group-id: testapp
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
logging:
  charset:
    file: UTF-8
  level:
    root: info
  file:
    path: log/


#---------------------------------
#基础配置
kafka:
  bootstrap: 192.168.56.101:9092

mainServer:
  ip: 127.0.0.1
  port: 22222

loginServer:
  ip: 127.0.0.1
  port: 11111
